from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "dist" / "my_bot.py"
SOURCE_MODULES = (
    ROOT / "bots" / "strategies" / "base.py",
    ROOT / "bots" / "strategies" / "features.py",
    ROOT / "bots" / "strategies" / "champion.py",
)
LOCAL_IMPORTS = {"strategies.base", "strategies.features"}

HEADER = '''from __future__ import annotations

# Generated by scripts/build_submission.py. Edit the source strategy modules,
# then rebuild this file. The official portal accepts one Python file only.
'''

ENTRYPOINT = '''

def main() -> None:
    game = Game()
    strategy = ChampionStrategy()

    while True:
        try:
            query = game.get_next_query()
        except EOFError:
            break

        match query:
            case QueryMovePlayer():
                decision = strategy.choose(StrategyContext(game=game, query=query))
                game.send_move(decision.to_move(game.state.me.player_id))
            case _:
                raise RuntimeError(f"Unsupported query type: {type(query)}")


if __name__ == "__main__":
    main()
'''


def _without_local_imports(path: Path) -> str:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    omitted_lines: set[int] = set()

    for node in tree.body:
        omit = isinstance(node, ast.ImportFrom) and (
            node.module == "__future__" or node.module in LOCAL_IMPORTS
        )
        if not omit:
            continue
        omitted_lines.update(range(node.lineno, (node.end_lineno or node.lineno) + 1))

    return "".join(
        line
        for line_number, line in enumerate(source.splitlines(keepends=True), start=1)
        if line_number not in omitted_lines
    ).strip()


def _validate_submission(source: str, output: Path) -> None:
    tree = ast.parse(source, filename=str(output))
    forbidden: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.split(".", 1)[0] in {"strategies", "bot_core", "telemetry"}:
                forbidden.append(node.module)
        elif isinstance(node, ast.Import):
            forbidden.extend(
                alias.name
                for alias in node.names
                if alias.name.split(".", 1)[0] in {"strategies", "bot_core", "telemetry"}
            )
    if forbidden:
        raise ValueError(f"Submission contains local imports: {sorted(set(forbidden))}")


def build_submission(output: Path = DEFAULT_OUTPUT) -> tuple[Path, str]:
    source_fingerprint = hashlib.sha256()
    sections: list[str] = [HEADER.rstrip()]
    for path in SOURCE_MODULES:
        source_fingerprint.update(path.read_bytes())
        source_fingerprint.update(b"\0")
        sections.append(_without_local_imports(path))

    fingerprint = source_fingerprint.hexdigest()
    sections.insert(1, f'# Source fingerprint: {fingerprint}')
    sections.append(ENTRYPOINT.strip())
    submission = "\n\n\n".join(sections) + "\n"
    _validate_submission(submission, output)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(submission, encoding="utf-8")
    digest = hashlib.sha256(submission.encode("utf-8")).hexdigest()
    return output, digest


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the single-file Bot Battle submission")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output, digest = build_submission(args.output.resolve())
    print(f"Built {output} ({output.stat().st_size} bytes, sha256={digest})")


if __name__ == "__main__":
    main()
