"""Build the current bot as the single Python file accepted by the portal."""

from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "dist" / "my_bot.py"
SOURCE_MODULES = (
    ROOT / "bots" / "strategies" / "base.py",
    ROOT / "bots" / "simulation" / "rules.py",
    ROOT / "bots" / "strategies" / "semantic_potential.py",
    ROOT / "bots" / "strategies" / "asset_preservation.py",
    ROOT / "bots" / "strategies" / "replay_distilled.py",
    ROOT / "bots" / "strategies" / "features.py",
)
LOCAL_IMPORTS = {
    "simulation.rules",
    "strategies.asset_preservation",
    "strategies.base",
    "strategies.features",
    "strategies.replay_distilled",
    "strategies.semantic_potential",
}

HEADER = '''from __future__ import annotations

# Generated by scripts/build_submission.py. Edit the modular sources, then rebuild.
'''

ENTRYPOINT = r'''
def _read_framed_message(connection) -> str:
    """Read the starter-kit length-prefixed JSON without 1 KiB recopy loops."""

    prefix: list[str] = []
    for _ in range(8):
        character = connection._from_engine_pipe.read(1)
        if character == "":
            raise EOFError("Engine closed the pipe.")
        if character == ",":
            break
        if not character.isdecimal():
            raise RuntimeError("Invalid engine message size prefix.")
        prefix.append(character)
    else:
        raise RuntimeError("Invalid engine message size prefix.")

    if not prefix:
        raise RuntimeError("Invalid engine message size prefix.")
    size = int("".join(prefix))
    if size > 1_000_000:
        raise RuntimeError("Engine message exceeds the starter-kit limit.")

    chunks: list[str] = []
    remaining = size
    while remaining:
        chunk = connection._from_engine_pipe.read(remaining)
        if chunk == "":
            raise EOFError("Engine closed the pipe.")
        chunks.append(chunk)
        remaining -= len(chunk)
    return "".join(chunks)


def _install_fast_query_reader(game: Game) -> None:
    connection = game.connection

    def get_next_query() -> QueryMovePlayer:
        return QueryMovePlayer.model_validate_json(_read_framed_message(connection))

    connection.get_next_query = get_next_query


def main() -> None:
    game = Game()
    _install_fast_query_reader(game)
    strategy = ReplayDistilledStrategy()

    while True:
        try:
            query = game.get_next_query()
        except EOFError:
            break
        if not isinstance(query, QueryMovePlayer):
            raise RuntimeError(f"Unsupported query type: {type(query)}")
        decision = strategy.choose(StrategyContext(game=game, query=query))
        game.send_move(decision.to_move(game.state.me.player_id))


if __name__ == "__main__":
    main()
'''


def _without_local_imports(path: Path) -> str:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    omitted_lines: set[int] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module == "__future__" or node.module in LOCAL_IMPORTS:
            omitted_lines.update(
                range(node.lineno, (node.end_lineno or node.lineno) + 1)
            )
    return "".join(
        line
        for line_number, line in enumerate(source.splitlines(keepends=True), start=1)
        if line_number not in omitted_lines
    ).strip()


def _validate_submission(source: str, output: Path) -> None:
    tree = ast.parse(source, filename=str(output))
    local_roots = {"simulation", "strategies", "telemetry"}
    forbidden: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.split(".", 1)[0] in local_roots:
                forbidden.add(node.module)
        elif isinstance(node, ast.Import):
            forbidden.update(
                alias.name
                for alias in node.names
                if alias.name.split(".", 1)[0] in local_roots
            )
    if forbidden:
        raise ValueError(f"Submission contains local imports: {sorted(forbidden)}")


def build_submission(output: Path = DEFAULT_OUTPUT) -> tuple[Path, str]:
    fingerprint = hashlib.sha256()
    sections = [HEADER.rstrip()]
    for path in SOURCE_MODULES:
        fingerprint.update(path.read_bytes())
        fingerprint.update(b"\0")
        sections.append(_without_local_imports(path))
    sections.insert(1, f"# Source fingerprint: {fingerprint.hexdigest()}")
    sections.append(ENTRYPOINT.strip())
    submission = "\n\n\n".join(sections) + "\n"
    _validate_submission(submission, output)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(submission, encoding="utf-8")
    digest = hashlib.sha256(submission.encode()).hexdigest()
    return output, digest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    output, digest = build_submission(args.output.resolve())
    print(f"Built {output} ({output.stat().st_size} bytes, sha256={digest})")


if __name__ == "__main__":
    main()
