from __future__ import annotations

# Generated by scripts/build_submission.py. Edit the source strategy modules,
# then rebuild this file. The official portal accepts one Python file only.


# Source fingerprint: 0652b69230aebe5220508ae770ba5a5f82bac5381ccf1a86786237825dfe58d0


from dataclasses import dataclass, field
from typing import Protocol

from helper.game import Game
from lib.interface.events.moves.move_player import MovePlayer
from lib.interface.queries.query_move import QueryMovePlayer
from lib.models.penguin_model import DirectionModel


@dataclass(frozen=True)
class StrategyContext:
    game: Game
    query: QueryMovePlayer


@dataclass(frozen=True)
class StrategyDecision:
    direction: tuple[float, float]
    split: bool = False
    target_kind: str = "none"
    target_id: str | None = None
    reason: str = ""
    score: float | None = None
    diagnostics: dict[str, object] = field(default_factory=dict)

    def to_move(self, player_id: int) -> MovePlayer:
        dx, dy = self.direction
        return MovePlayer(
            player_id=player_id,
            direction=DirectionModel(x=dx, y=dy),
            split=self.split,
        )


class Strategy(Protocol):
    name: str

    def choose(self, context: StrategyContext) -> StrategyDecision:
        raise NotImplementedError


import math
from dataclasses import dataclass
from typing import Iterable

from helper.game import Game
from lib.config.player import EAT_SIZE_RATIO
from lib.models.blob_model import BlobModel, VisibleBlobModel
from lib.models.food_model import FoodModel
from lib.models.virus_model import VirusModel


@dataclass(frozen=True)
class BlobRelation:
    blob: VisibleBlobModel
    nearest_own_blob: BlobModel
    distance: float
    can_eat_us: bool
    can_be_eaten: bool

    @property
    def danger_margin(self) -> float:
        return self.distance - self.blob.radius


@dataclass(frozen=True)
class VisibleFeatures:
    own_blobs: tuple[BlobModel, ...]
    predators: tuple[BlobRelation, ...]
    prey: tuple[BlobRelation, ...]
    neutral: tuple[BlobRelation, ...]
    nearest_food: FoodModel | None
    nearest_food_distance: float | None
    nearest_predator: BlobRelation | None
    nearest_prey: BlobRelation | None
    nearest_virus: VirusModel | None
    nearest_virus_distance: float | None


def squared_distance(a: tuple[float, float], b: tuple[float, float]) -> float:
    dx = a[0] - b[0]
    dy = a[1] - b[1]
    return dx * dx + dy * dy


def distance(a: tuple[float, float], b: tuple[float, float]) -> float:
    return math.sqrt(squared_distance(a, b))


def vector_from_to(a: tuple[float, float], b: tuple[float, float]) -> tuple[float, float]:
    return (b[0] - a[0], b[1] - a[1])


def vector_magnitude(vector: tuple[float, float]) -> float:
    return math.hypot(vector[0], vector[1])


def normalise(vector: tuple[float, float]) -> tuple[float, float]:
    magnitude = vector_magnitude(vector)
    if magnitude == 0.0 or not math.isfinite(magnitude):
        return (0.0, 0.0)
    return (vector[0] / magnitude, vector[1] / magnitude)


def can_eat_player_blob(
    eater_radius: float,
    target_radius: float,
    radius_margin: float = 1.0,
) -> bool:
    """Return the engine's mass-ratio eating rule in radius coordinates."""

    return eater_radius * eater_radius >= (
        target_radius
        * target_radius
        * EAT_SIZE_RATIO
        * radius_margin
        * radius_margin
    )


def nearest_to_any_blob(
    own_blobs: tuple[BlobModel, ...],
    items: Iterable[FoodModel | VirusModel],
) -> tuple[FoodModel | VirusModel | None, float | None]:
    nearest_item = None
    nearest_distance_squared = None
    for item in items:
        for blob in own_blobs:
            distance_squared = squared_distance(blob.pos, item.pos)
            if (
                nearest_distance_squared is None
                or distance_squared < nearest_distance_squared
            ):
                nearest_item = item
                nearest_distance_squared = distance_squared
    return (
        nearest_item,
        math.sqrt(nearest_distance_squared)
        if nearest_distance_squared is not None
        else None,
    )


def _own_blobs(game: Game) -> tuple[BlobModel, ...]:
    return tuple(game.state.me.blobs.values())


def _nearest_own_blob(
    own_blobs: tuple[BlobModel, ...],
    visible_blob: VisibleBlobModel,
) -> tuple[BlobModel, float]:
    nearest = min(
        own_blobs,
        key=lambda own_blob: squared_distance(own_blob.pos, visible_blob.pos),
    )
    return nearest, distance(nearest.pos, visible_blob.pos)


def _relation_for_blob(
    own_blobs: tuple[BlobModel, ...],
    visible_blob: VisibleBlobModel,
) -> BlobRelation:
    vulnerable_blobs = tuple(
        own_blob
        for own_blob in own_blobs
        if can_eat_player_blob(visible_blob.radius, own_blob.radius)
    )
    capable_eaters = tuple(
        own_blob
        for own_blob in own_blobs
        if can_eat_player_blob(own_blob.radius, visible_blob.radius)
    )

    # A split player can have a large blob that is safe beside a small blob the
    # same enemy can consume.  Measure threats from the nearest *vulnerable*
    # blob; using the nearest arbitrary blob can point the shared movement in
    # exactly the wrong escape direction.  For prey, use the nearest blob that
    # is actually large enough to eat it.
    relevant_own_blobs = vulnerable_blobs or capable_eaters or own_blobs
    nearest_own_blob, blob_distance = _nearest_own_blob(relevant_own_blobs, visible_blob)
    return BlobRelation(
        blob=visible_blob,
        nearest_own_blob=nearest_own_blob,
        distance=blob_distance,
        can_eat_us=bool(vulnerable_blobs),
        can_be_eaten=bool(capable_eaters),
    )


def extract_visible_features(game: Game) -> VisibleFeatures:
    own_blobs = _own_blobs(game)
    if not own_blobs:
        return VisibleFeatures(
            own_blobs=(),
            predators=(),
            prey=(),
            neutral=(),
            nearest_food=None,
            nearest_food_distance=None,
            nearest_predator=None,
            nearest_prey=None,
            nearest_virus=None,
            nearest_virus_distance=None,
        )

    relations = [
        _relation_for_blob(own_blobs, visible_blob)
        for visible_blob in game.state.visible_blobs
    ]
    predators = tuple(relation for relation in relations if relation.can_eat_us)
    # Keep the categories disjoint.  In particular, a blob that can eat one of
    # our small fragments is not "safe prey" merely because a different, large
    # fragment could eat it.
    prey = tuple(
        relation
        for relation in relations
        if relation.can_be_eaten and not relation.can_eat_us
    )
    neutral = tuple(
        relation
        for relation in relations
        if not relation.can_eat_us and not relation.can_be_eaten
    )
    nearest_food, nearest_food_distance = nearest_to_any_blob(
        own_blobs,
        game.state.visible_food,
    )
    nearest_virus, nearest_virus_distance = nearest_to_any_blob(
        own_blobs,
        game.state.visible_viruses,
    )

    return VisibleFeatures(
        own_blobs=own_blobs,
        predators=predators,
        prey=prey,
        neutral=neutral,
        nearest_food=nearest_food if isinstance(nearest_food, FoodModel) else None,
        nearest_food_distance=nearest_food_distance,
        nearest_predator=min(predators, key=lambda relation: relation.danger_margin)
        if predators
        else None,
        nearest_prey=min(prey, key=lambda relation: relation.distance) if prey else None,
        nearest_virus=nearest_virus if isinstance(nearest_virus, VirusModel) else None,
        nearest_virus_distance=nearest_virus_distance,
    )


"""Robust receding-horizon strategy used by the submission entry point.

The strategy deliberately separates prediction from evaluation:

* opponent movement events are optional because current competition payloads
  censor them;
* predators are rolled forward adversarially when no public direction exists,
  so censored or stale movement never makes an unsafe line look safe;
* own movement, splitting, eject velocity, decay, food, and eating follow the
  engine's update order closely;
* semantic actions are ordered by safety and usefulness, allowing the search
  to return its best completed root candidate when the time budget expires.

Only standard-library code and public agario-kit models are used at runtime.
"""

import math
import os
from dataclasses import dataclass, field, replace
from time import perf_counter

from lib.config.arena import ARENA_SIZE, MAX_BLOB_COUNT
from lib.config.player import (
    BASE_PLAYER_SPEED,
    EAT_SIZE_RATIO,
    FOOD_RADIUS,
    MASS_DECAY_RATE,
    MERGE_ATTRACTION_SPEED,
    MIN_PLAYER_SPEED,
    PLAYER_SPEED_RADIUS_FACTOR,
    SAME_PLAYER_OVERLAP_EPSILON,
    SPLIT_COOLDOWN_FRAMES,
    SPLIT_EJECT_DRAG,
    SPLIT_EJECT_SPEED,
    SPLIT_MIN_MASS,
    STARTING_RADIUS,
)
from lib.interface.events.moves.move_player import MovePlayer
from lib.models.food_model import FoodModel
from lib.models.virus_model import VirusModel


SQRT2 = math.sqrt(2.0)
TAU = 2.0 * math.pi
EPSILON = 1e-9


@dataclass(frozen=True)
class Action:
    direction: tuple[float, float]
    split: bool = False
    reason: str = "move"


@dataclass(frozen=True)
class OwnBlob:
    blob_id: int
    x: float
    y: float
    radius: float
    merge_cooldown: int = 0
    eject_vx: float = 0.0
    eject_vy: float = 0.0

    @property
    def pos(self) -> tuple[float, float]:
        return (self.x, self.y)

    @property
    def mass(self) -> float:
        return self.radius * self.radius


@dataclass(frozen=True)
class EnemyBlob:
    player_id: int
    blob_id: int
    x: float
    y: float
    radius: float
    direction: tuple[float, float] = (0.0, 0.0)
    stale_rounds: int = 0

    @property
    def key(self) -> tuple[int, int]:
        return (self.player_id, self.blob_id)

    @property
    def pos(self) -> tuple[float, float]:
        return (self.x, self.y)

    @property
    def mass(self) -> float:
        return self.radius * self.radius


@dataclass(frozen=True)
class EnemyTrack:
    player_id: int
    blob_id: int
    x: float
    y: float
    radius: float
    direction: tuple[float, float]
    last_seen_round: int


@dataclass(frozen=True)
class SearchNode:
    own_blobs: tuple[OwnBlob, ...]
    enemies: tuple[EnemyBlob, ...]
    score: float
    first_direction: tuple[float, float]
    first_split: bool
    first_reason: str
    last_direction: tuple[float, float]
    eaten_food_ids: frozenset[int] = field(default_factory=frozenset)
    captured_enemy_ids: frozenset[tuple[int, int]] = field(default_factory=frozenset)
    consumed_virus_ids: frozenset[int] = field(default_factory=frozenset)
    projected_food: int = 0
    projected_captures: int = 0
    min_safety_margin: float = math.inf

    @property
    def total_mass(self) -> float:
        return sum(blob.mass for blob in self.own_blobs)

    @property
    def primary(self) -> OwnBlob:
        return max(self.own_blobs, key=lambda blob: blob.radius)

    @property
    def center(self) -> tuple[float, float]:
        total_mass = self.total_mass
        if total_mass <= EPSILON:
            return self.primary.pos
        return (
            sum(blob.x * blob.mass for blob in self.own_blobs) / total_mass,
            sum(blob.y * blob.mass for blob in self.own_blobs) / total_mass,
        )


@dataclass(frozen=True)
class StepResult:
    node: SearchNode
    fatal: bool = False


class ChampionStrategy:
    """Threat-first beam search with exact public-rule tactical simulation."""

    name = "champion"

    def __init__(
        self,
        depth: int | None = None,
        width: int | None = None,
        angular_samples: int | None = None,
    ) -> None:
        # These defaults stay comfortably below the engine's eight-second
        # cumulative budget while still searching substantially more first
        # actions than the older beam strategies.
        self.depth = depth if depth is not None else int(os.environ.get("BOT_CHAMPION_DEPTH", "3"))
        self.width = width if width is not None else int(os.environ.get("BOT_CHAMPION_WIDTH", "4"))
        self.angular_samples = (
            angular_samples
            if angular_samples is not None
            else int(os.environ.get("BOT_CHAMPION_ANGLES", "18"))
        )
        self.max_food = int(os.environ.get("BOT_CHAMPION_MAX_FOOD", "24"))
        self.max_enemies = int(os.environ.get("BOT_CHAMPION_MAX_ENEMIES", "12"))
        # The engine's eight-second cumulative limit includes pipe I/O, model
        # validation, and state updates outside this strategy. Reserve nearly
        # half of it for that runtime overhead instead of spending it on search.
        self.compute_budget_seconds = float(os.environ.get("BOT_CHAMPION_TOTAL_BUDGET_SECONDS", "4.2"))
        self.max_turn_seconds = float(os.environ.get("BOT_CHAMPION_MAX_TURN_SECONDS", "0.003"))
        self.min_search_seconds = float(os.environ.get("BOT_CHAMPION_MIN_SEARCH_SECONDS", "0.00075"))
        self.compute_spent_seconds = 0.0
        self.previous_direction: tuple[float, float] = (1.0, 0.0)
        self.last_moves: dict[int, tuple[tuple[float, float], bool]] = {}
        self.enemy_tracks: dict[tuple[int, int], EnemyTrack] = {}

    def choose(self, context: StrategyContext) -> StrategyDecision:
        started_at = perf_counter()
        state = context.game.state
        turn_budget = self._turn_budget_seconds(
            round_number=int(state.round),
            max_rounds=int(state.max_rounds),
        )
        try:
            if turn_budget < self.min_search_seconds:
                return self._time_budget_fallback(context)
            return self._choose(
                context,
                deadline=started_at + turn_budget,
                turn_budget=turn_budget,
            )
        finally:
            self.compute_spent_seconds += perf_counter() - started_at

    def _choose(
        self,
        context: StrategyContext,
        *,
        deadline: float,
        turn_budget: float,
    ) -> StrategyDecision:
        state = context.game.state
        own_blobs = tuple(
            OwnBlob(
                blob_id=blob.blob_id,
                x=blob.pos[0],
                y=blob.pos[1],
                radius=blob.radius,
                merge_cooldown=blob.merge_cooldown,
            )
            for blob in state.me.blobs.values()
        )
        if not own_blobs:
            return StrategyDecision(direction=self.previous_direction, reason="dead_fallback")

        round_number = int(state.round)
        arena_size = float(state.map.size or ARENA_SIZE)
        self._read_public_moves(context)
        enemies = self._update_enemy_memory(context, own_blobs, arena_size)

        center = self._mass_center(own_blobs)
        foods = tuple(
            sorted(
                state.visible_food,
                key=lambda food: (
                    min(squared_distance(blob.pos, food.pos) for blob in own_blobs),
                    squared_distance(center, food.pos),
                ),
            )[: self.max_food]
        )
        viruses = tuple(state.visible_viruses)
        enemies = tuple(
            sorted(
                enemies,
                key=lambda enemy: squared_distance(center, enemy.pos),
            )[: self.max_enemies]
        )
        # Clustering is quadratic in the number of food items. It depends only
        # on the authoritative current observation, so compute it once rather
        # than once for every rollout node.
        food_targets = tuple(self._food_targets(center, list(foods)))

        rank_position = self._rank_position(state.rankings, state.me.player_id)
        progress = round_number / max(1, int(state.max_rounds))
        direct_virus = self._direct_virus_decision(
            own_blobs=own_blobs,
            enemies=enemies,
            viruses=viruses,
            arena_size=arena_size,
            rank_position=rank_position,
            progress=progress,
        )
        if direct_virus is not None:
            self.previous_direction = direct_virus.direction
            return StrategyDecision(
                direction=direct_virus.direction,
                split=direct_virus.split,
                target_kind="virus",
                reason=direct_virus.reason,
                diagnostics={
                    "direct_virus": True,
                    "rank": rank_position,
                    "progress": round(progress, 4),
                    "visible_or_tracked_enemies": len(enemies),
                    "turn_budget_ms": round(turn_budget * 1000.0, 3),
                    "compute_spent_ms": round(self.compute_spent_seconds * 1000.0, 3),
                },
            )

        start = SearchNode(
            own_blobs=own_blobs,
            enemies=enemies,
            score=0.0,
            first_direction=self.previous_direction,
            first_split=False,
            first_reason="keep",
            last_direction=self.previous_direction,
        )
        safety_weight = self._safety_weight(rank_position, progress)
        aggression = self._aggression(rank_position, progress)

        beam = [start]
        best_rejected: SearchNode | None = None
        reached_depth = 0
        search_timed_out = False
        for depth_index in range(max(1, self.depth)):
            candidates: list[SearchNode] = []
            depth_timed_out = False
            evaluated_actions = 0
            for node in beam:
                actions = self._candidate_actions(
                    node=node,
                    foods=foods,
                    food_targets=food_targets,
                    viruses=viruses,
                    arena_size=arena_size,
                    first_step=depth_index == 0,
                    allow_split=not (progress >= 0.78 and rank_position <= 2),
                    angle_offset=round_number,
                )
                for action in actions:
                    # Evaluate at least one action at each depth, then stop at
                    # the deadline. Root actions are safety-first, so a partial
                    # root remains useful; partial deeper layers are discarded.
                    if evaluated_actions and perf_counter() >= deadline:
                        depth_timed_out = True
                        break
                    result = self._step(
                        node=node,
                        action=action,
                        foods=foods,
                        viruses=viruses,
                        arena_size=arena_size,
                        first_step=depth_index == 0,
                        safety_weight=safety_weight,
                        aggression=aggression,
                    )
                    evaluated_actions += 1
                    if result.fatal:
                        if best_rejected is None or result.node.score > best_rejected.score:
                            best_rejected = result.node
                        continue
                    candidates.append(result.node)
                if depth_timed_out:
                    break

            if depth_timed_out:
                search_timed_out = True
                if depth_index == 0 and candidates:
                    beam = self._prune(candidates)
                    reached_depth = 1
                break
            if not candidates:
                break
            beam = self._prune(candidates)
            reached_depth = depth_index + 1
            if perf_counter() >= deadline:
                search_timed_out = True
                break

        if beam and reached_depth:
            best = max(beam, key=self._terminal_score)
            reason = best.first_reason
        elif best_rejected is not None:
            best = best_rejected
            reason = "least_bad_escape"
        else:
            best = start
            reason = "no_search_result"

        direction = normalise(best.first_direction) or self.previous_direction
        self.previous_direction = direction
        return StrategyDecision(
            direction=direction,
            split=best.first_split,
            target_kind="escape" if "escape" in reason else ("prey" if "prey" in reason else "beam"),
            reason=reason,
            score=self._terminal_score(best),
            diagnostics={
                "depth": reached_depth,
                "width": self.width,
                "angles": self.angular_samples,
                "rank": rank_position,
                "progress": round(progress, 4),
                "visible_or_tracked_enemies": len(enemies),
                "projected_food": best.projected_food,
                "projected_captures": best.projected_captures,
                "projected_blob_count": len(best.own_blobs),
                "min_safety_margin": best.min_safety_margin,
                "search_timed_out": search_timed_out,
                "turn_budget_ms": round(turn_budget * 1000.0, 3),
                "compute_spent_ms": round(self.compute_spent_seconds * 1000.0, 3),
            },
        )

    def _turn_budget_seconds(self, *, round_number: int, max_rounds: int) -> float:
        remaining_budget = max(0.0, self.compute_budget_seconds - self.compute_spent_seconds)
        remaining_rounds = max(1, max_rounds - round_number)
        return min(self.max_turn_seconds, remaining_budget / remaining_rounds)

    def _time_budget_fallback(self, context: StrategyContext) -> StrategyDecision:
        """Return a cheap visible-state action after the search bank is spent."""

        state = context.game.state
        own_blobs = tuple(state.me.blobs.values())
        if not own_blobs:
            return StrategyDecision(direction=self.previous_direction, reason="time_bank_dead")

        away_x = 0.0
        away_y = 0.0
        for enemy in state.visible_blobs:
            if not any(
                can_eat_player_blob(enemy.radius, own.radius)
                for own in own_blobs
            ):
                continue
            nearest = min(own_blobs, key=lambda own: squared_distance(own.pos, enemy.pos))
            distance = max(math.dist(nearest.pos, enemy.pos), 0.25)
            away_x += (nearest.pos[0] - enemy.pos[0]) * enemy.radius / (distance * distance)
            away_y += (nearest.pos[1] - enemy.pos[1]) * enemy.radius / (distance * distance)

        direction = normalise((away_x, away_y))
        reason = "time_bank_escape"
        if direction == (0.0, 0.0) and state.visible_food:
            pairs = [
                (squared_distance(blob.pos, food.pos), blob, food)
                for blob in own_blobs
                for food in state.visible_food
            ]
            _, origin, food = min(pairs, key=lambda item: item[0])
            direction = normalise((food.pos[0] - origin.pos[0], food.pos[1] - origin.pos[1]))
            reason = "time_bank_food"
        if direction == (0.0, 0.0):
            direction = self.previous_direction
            reason = "time_bank_keep"

        self.previous_direction = direction
        return StrategyDecision(
            direction=direction,
            target_kind="escape" if reason == "time_bank_escape" else "food",
            reason=reason,
            diagnostics={
                "compute_spent_ms": round(self.compute_spent_seconds * 1000.0, 3),
                "compute_budget_ms": round(self.compute_budget_seconds * 1000.0, 3),
            },
        )

    def _read_public_moves(self, context: StrategyContext) -> None:
        for event in context.query.update.values():
            if not isinstance(event, MovePlayer):
                continue
            direction = normalise(event.direction.to_vector())
            self.last_moves[event.player_id] = (direction, bool(event.split))

    def _update_enemy_memory(
        self,
        context: StrategyContext,
        own_blobs: tuple[OwnBlob, ...],
        arena_size: float,
    ) -> tuple[EnemyBlob, ...]:
        state = context.game.state
        round_number = int(state.round)
        visible_keys: set[tuple[int, int]] = set()

        # Current competition payloads censor opponent movement. Advance an
        # unseen predator toward the nearest vulnerable fragment unless an
        # explicit public move is available. Visible data below always replaces
        # this conservative estimate.
        advanced: dict[tuple[int, int], EnemyTrack] = {}
        for key, track in self.enemy_tracks.items():
            observed_move = self.last_moves.get(track.player_id)
            if observed_move is not None:
                direction = observed_move[0]
            else:
                vulnerable = tuple(
                    own
                    for own in own_blobs
                    if can_eat_player_blob(track.radius, own.radius)
                )
                if vulnerable:
                    target = min(
                        vulnerable,
                        key=lambda own: squared_distance((track.x, track.y), own.pos),
                    )
                    direction = normalise((target.x - track.x, target.y - track.y))
                else:
                    direction = track.direction
            speed = _speed(track.radius)
            radius = _decayed_radius(track.radius)
            advanced[key] = replace(
                track,
                x=_clamp(track.x + direction[0] * speed, radius, arena_size - radius),
                y=_clamp(track.y + direction[1] * speed, radius, arena_size - radius),
                radius=radius,
                direction=direction,
            )

        for blob in state.visible_blobs:
            key = (blob.player_id, blob.blob_id)
            visible_keys.add(key)
            direction = self.last_moves.get(blob.player_id, ((0.0, 0.0), False))[0]
            advanced[key] = EnemyTrack(
                player_id=blob.player_id,
                blob_id=blob.blob_id,
                x=blob.pos[0],
                y=blob.pos[1],
                radius=blob.radius,
                direction=direction,
                last_seen_round=round_number,
            )

        view_center = tuple(state.view_center)
        half_view = float(state.vision_size) / 2.0
        kept: dict[tuple[int, int], EnemyTrack] = {}
        enemies: list[EnemyBlob] = []
        largest_own = max(blob.radius for blob in own_blobs)
        for key, track in advanced.items():
            stale_rounds = round_number - track.last_seen_round
            if stale_rounds > 10:
                continue
            should_be_visible = (
                abs(track.x - view_center[0]) <= half_view + track.radius
                and abs(track.y - view_center[1]) <= half_view + track.radius
            )
            if key not in visible_keys and should_be_visible:
                # The estimate contradicted the authoritative current view.
                continue
            kept[key] = track
            # Stale prey is never chased. Retain only potentially dangerous
            # stale blobs close enough to matter within this search horizon.
            if stale_rounds and not can_eat_player_blob(track.radius, largest_own):
                continue
            enemies.append(
                EnemyBlob(
                    player_id=track.player_id,
                    blob_id=track.blob_id,
                    x=track.x,
                    y=track.y,
                    radius=track.radius,
                    direction=track.direction,
                    stale_rounds=stale_rounds,
                )
            )
        self.enemy_tracks = kept
        return tuple(enemies)

    def _candidate_actions(
        self,
        *,
        node: SearchNode,
        foods: tuple[FoodModel, ...],
        food_targets: tuple[tuple[float, float], ...],
        viruses: tuple[VirusModel, ...],
        arena_size: float,
        first_step: bool,
        allow_split: bool,
        angle_offset: int = 0,
    ) -> tuple[Action, ...]:
        actions: list[Action] = []

        # This order is part of the anytime-search contract: if the root is
        # cut short, it must already have considered the tactically important
        # options rather than an arbitrary prefix of the angular grid.
        escape = self._escape_vector(node)
        if escape != (0.0, 0.0):
            actions.append(Action(escape, reason="escape"))
            # Tangential options often escape a wall/predator pincer better
            # than a pure potential-field vector.
            actions.append(Action(_rotate(escape, math.pi / 8), reason="escape_tangent"))
            actions.append(Action(_rotate(escape, -math.pi / 8), reason="escape_tangent"))

        # Virus farming is high value in this ruleset, but unsafe when it
        # creates many bite-sized fragments near predators.  Add it before
        # food so an anytime root search can still consider a safe virus.
        actions.extend(
            self._virus_actions(
                node=node,
                viruses=viruses,
                arena_size=arena_size,
                limit=3 if first_step else 1,
            )
        )

        center = node.center
        available_food = [food for food in foods if food.food_id not in node.eaten_food_ids]
        if available_food:
            # Food is a one-step resource and the search is explicitly
            # anytime. Put the nearest reachable-food candidates before
            # inertia, otherwise a tight turn budget can spend the root on
            # "keep" and never evaluate the food collection move.  The origin
            # is the fragment that can reach the food first, not the mass
            # centre; this matters most after splitting and along walls.
            food_pairs = self._nearest_food_pairs(node, available_food)
            for origin, food in food_pairs[: 4 if first_step else 2]:
                actions.append(
                    Action(
                        normalise((food.pos[0] - origin.x, food.pos[1] - origin.y)),
                        reason="fragment_food",
                    )
                )
            actions.extend(
                self._edge_food_actions(
                    node=node,
                    foods=available_food,
                    arena_size=arena_size,
                    limit=4 if first_step else 2,
                )
            )
            nearest_food = min(available_food, key=lambda food: squared_distance(center, food.pos))
            actions.append(
                Action(
                    normalise((nearest_food.pos[0] - center[0], nearest_food.pos[1] - center[1])),
                    reason="nearest_food",
                )
            )
        target_limit = 4 if first_step else 2
        for target in food_targets[:target_limit]:
            actions.append(Action(normalise((target[0] - center[0], target[1] - center[1])), reason="food_cluster"))

        actions.append(Action(node.last_direction, reason="keep" if first_step else "continue"))
        if not first_step:
            for angle in (-math.pi / 6, -math.pi / 12, math.pi / 12, math.pi / 6):
                actions.append(Action(_rotate(node.last_direction, angle), reason="steer"))

        prey = [
            enemy
            for enemy in node.enemies
            if enemy.stale_rounds == 0
            and any(
                can_eat_player_blob(own.radius, enemy.radius)
                for own in node.own_blobs
            )
        ]
        prey.sort(key=lambda enemy: squared_distance(center, enemy.pos))
        for enemy in prey[: 3 if first_step else 2]:
            intercept = self._intercept_direction(node.primary, enemy)
            actions.append(Action(intercept, reason="prey"))
            if allow_split and self._split_can_capture(node, enemy, intercept):
                actions.append(Action(intercept, split=True, reason="split_prey"))

        if allow_split:
            farm_action = self._safe_farm_split(node, available_food, food_targets)
            if farm_action is not None:
                actions.append(farm_action)

        wall = self._wall_vector(node.primary, arena_size)
        if wall != (0.0, 0.0):
            actions.append(Action(wall, reason="wall_escape"))
        actions.append(Action(normalise((arena_size / 2.0 - center[0], arena_size / 2.0 - center[1])), reason="center"))

        if first_step:
            sample_count = max(8, self.angular_samples)
            actions.extend(
                Action(
                    (
                        math.cos(TAU * ((index + angle_offset) % sample_count) / sample_count),
                        math.sin(TAU * ((index + angle_offset) % sample_count) / sample_count),
                    ),
                    reason="angle",
                )
                for index in range(sample_count)
            )

        return self._dedupe_actions(actions)

    def _step(
        self,
        *,
        node: SearchNode,
        action: Action,
        foods: tuple[FoodModel, ...],
        viruses: tuple[VirusModel, ...],
        arena_size: float,
        first_step: bool,
        safety_weight: float,
        aggression: float,
    ) -> StepResult:
        direction = normalise(action.direction)
        own_blobs = list(node.own_blobs)
        score = node.score
        if action.split:
            own_blobs = self._apply_split(own_blobs, direction, arena_size)
            score -= 6.0 + max(0, len(own_blobs) - len(node.own_blobs)) * 1.5

        own_blobs = [self._move_own(blob, direction, arena_size) for blob in own_blobs]
        own_blobs = self._apply_attraction(own_blobs, arena_size)
        enemies = self._move_enemies(node.enemies, own_blobs, arena_size)

        eaten_food_ids = set(node.eaten_food_ids)
        captured_enemy_ids = set(node.captured_enemy_ids)
        consumed_virus_ids = set(node.consumed_virus_ids)
        projected_food = node.projected_food
        projected_captures = node.projected_captures

        own_blobs = [replace(blob, radius=_decayed_radius(blob.radius)) for blob in own_blobs]
        for food in foods:
            if food.food_id in eaten_food_ids:
                continue
            candidates = [
                index
                for index, blob in enumerate(own_blobs)
                if squared_distance(blob.pos, food.pos) <= blob.radius * blob.radius
            ]
            if not candidates:
                continue
            index = max(candidates, key=lambda item: own_blobs[item].radius)
            eater = own_blobs[index]
            own_blobs[index] = replace(eater, radius=math.sqrt(eater.mass + FOOD_RADIUS * FOOD_RADIUS))
            eaten_food_ids.add(food.food_id)
            projected_food += 1
            score += 7.0

        own_blobs, virus_score, virus_penalty = self._resolve_own_viruses(
            own_blobs=own_blobs,
            viruses=viruses,
            consumed_virus_ids=consumed_virus_ids,
            arena_size=arena_size,
        )
        score += virus_score
        score -= virus_penalty * safety_weight

        own_blobs, enemies, interaction_score, captures = self._resolve_interactions(
            own_blobs,
            enemies,
            captured_enemy_ids,
        )
        projected_captures += captures
        score += interaction_score * aggression
        if not own_blobs:
            dead = self._replace_node(
                node=node,
                own_blobs=(),
                enemies=enemies,
                score=score - 100_000.0,
                direction=direction,
                action=action,
                first_step=first_step,
                eaten_food_ids=eaten_food_ids,
                captured_enemy_ids=captured_enemy_ids,
                consumed_virus_ids=consumed_virus_ids,
                projected_food=projected_food,
                projected_captures=projected_captures,
                min_safety_margin=-math.inf,
            )
            return StepResult(dead, fatal=True)

        risk_penalty, min_margin, unavoidable = self._risk_score(own_blobs, enemies, safety_weight)
        score -= risk_penalty
        score += self._position_value(own_blobs, enemies, foods, eaten_food_ids, arena_size, aggression)
        score -= self._turn_cost(node.last_direction, direction)
        score -= max(0, len(own_blobs) - 1) * 0.65

        next_node = self._replace_node(
            node=node,
            own_blobs=tuple(own_blobs),
            enemies=enemies,
            score=score,
            direction=direction,
            action=action,
            first_step=first_step,
            eaten_food_ids=eaten_food_ids,
            captured_enemy_ids=captured_enemy_ids,
            consumed_virus_ids=consumed_virus_ids,
            projected_food=projected_food,
            projected_captures=projected_captures,
            min_safety_margin=min(node.min_safety_margin, min_margin),
        )
        # A negative split margin means a rational predator can consume every
        # remaining fragment immediately. Reject only when all own blobs are in
        # that envelope; otherwise the mass-loss penalty already prices it.
        return StepResult(next_node, fatal=unavoidable)

    def _apply_split(
        self,
        blobs: list[OwnBlob],
        direction: tuple[float, float],
        arena_size: float,
    ) -> list[OwnBlob]:
        result = list(blobs)
        starting_ids = [blob.blob_id for blob in sorted(blobs, key=lambda blob: blob.blob_id)]
        next_id = max(starting_ids, default=-1) + 1
        by_id = {blob.blob_id: blob for blob in result}
        for blob_id in starting_ids:
            if len(by_id) >= MAX_BLOB_COUNT:
                break
            blob = by_id.get(blob_id)
            if blob is None or blob.mass < SPLIT_MIN_MASS:
                continue
            child_radius = blob.radius / SQRT2
            parent = replace(blob, radius=child_radius, merge_cooldown=SPLIT_COOLDOWN_FRAMES)
            child = OwnBlob(
                blob_id=next_id,
                x=_clamp(
                    blob.x + direction[0] * (2.0 * child_radius + SAME_PLAYER_OVERLAP_EPSILON),
                    child_radius,
                    arena_size - child_radius,
                ),
                y=_clamp(
                    blob.y + direction[1] * (2.0 * child_radius + SAME_PLAYER_OVERLAP_EPSILON),
                    child_radius,
                    arena_size - child_radius,
                ),
                radius=child_radius,
                merge_cooldown=SPLIT_COOLDOWN_FRAMES,
                eject_vx=direction[0] * SPLIT_EJECT_SPEED,
                eject_vy=direction[1] * SPLIT_EJECT_SPEED,
            )
            by_id[blob_id] = parent
            by_id[next_id] = child
            next_id += 1
        return list(by_id.values())

    def _move_own(self, blob: OwnBlob, direction: tuple[float, float], arena_size: float) -> OwnBlob:
        x = blob.x + direction[0] * _speed(blob.radius) + blob.eject_vx
        y = blob.y + direction[1] * _speed(blob.radius) + blob.eject_vy
        return OwnBlob(
            blob_id=blob.blob_id,
            x=_clamp(x, blob.radius, arena_size - blob.radius),
            y=_clamp(y, blob.radius, arena_size - blob.radius),
            radius=blob.radius,
            merge_cooldown=max(0, blob.merge_cooldown - 1),
            eject_vx=_damped(blob.eject_vx),
            eject_vy=_damped(blob.eject_vy),
        )

    def _apply_attraction(self, blobs: list[OwnBlob], arena_size: float) -> list[OwnBlob]:
        if len(blobs) <= 1:
            return blobs
        total_mass = sum(blob.mass for blob in blobs)
        center_x = sum(blob.x * blob.mass for blob in blobs) / total_mass
        center_y = sum(blob.y * blob.mass for blob in blobs) / total_mass
        result: list[OwnBlob] = []
        for blob in blobs:
            dx = center_x - blob.x
            dy = center_y - blob.y
            distance = math.hypot(dx, dy)
            if distance <= EPSILON:
                result.append(blob)
                continue
            step = min(MERGE_ATTRACTION_SPEED, distance)
            result.append(
                replace(
                    blob,
                    x=_clamp(blob.x + dx / distance * step, blob.radius, arena_size - blob.radius),
                    y=_clamp(blob.y + dy / distance * step, blob.radius, arena_size - blob.radius),
                )
            )
        return result

    def _move_enemies(
        self,
        enemies: tuple[EnemyBlob, ...],
        own_blobs: list[OwnBlob],
        arena_size: float,
    ) -> tuple[EnemyBlob, ...]:
        moved: list[EnemyBlob] = []
        for enemy in enemies:
            target = min(own_blobs, key=lambda own: squared_distance(enemy.pos, own.pos))
            observed = normalise(enemy.direction)
            if can_eat_player_blob(enemy.radius, target.radius):
                adversarial = normalise((target.x - enemy.x, target.y - enemy.y))
                direction = normalise((
                    adversarial[0] * 0.82 + observed[0] * 0.18,
                    adversarial[1] * 0.82 + observed[1] * 0.18,
                ))
            elif any(
                can_eat_player_blob(own.radius, enemy.radius)
                for own in own_blobs
            ):
                hunter = min(own_blobs, key=lambda own: squared_distance(enemy.pos, own.pos))
                flee = normalise((enemy.x - hunter.x, enemy.y - hunter.y))
                direction = normalise((
                    flee[0] * 0.62 + observed[0] * 0.38,
                    flee[1] * 0.62 + observed[1] * 0.38,
                ))
            else:
                direction = observed
            speed = _speed(enemy.radius)
            moved.append(
                replace(
                    enemy,
                    x=_clamp(enemy.x + direction[0] * speed, enemy.radius, arena_size - enemy.radius),
                    y=_clamp(enemy.y + direction[1] * speed, enemy.radius, arena_size - enemy.radius),
                    radius=_decayed_radius(enemy.radius),
                    direction=direction,
                )
            )
        return tuple(moved)

    def _resolve_interactions(
        self,
        own_blobs: list[OwnBlob],
        enemies: tuple[EnemyBlob, ...],
        captured_enemy_ids: set[tuple[int, int]],
    ) -> tuple[list[OwnBlob], tuple[EnemyBlob, ...], float, int]:
        survivors = list(own_blobs)
        remaining = list(enemies)
        score = 0.0
        captures = 0

        # The engine resolves larger eaters first. Handle enemy consumption
        # before own captures so optimistic mutual-eat states cannot survive.
        for enemy in sorted(remaining, key=lambda item: item.radius, reverse=True):
            eaten = [
                index
                for index, own in enumerate(survivors)
                if can_eat_player_blob(enemy.radius, own.radius)
                and squared_distance(enemy.pos, own.pos) <= enemy.radius * enemy.radius
            ]
            for index in sorted(eaten, reverse=True):
                lost = survivors.pop(index)
                score -= 520.0 + lost.mass * 90.0
            if not survivors:
                return [], tuple(remaining), score, captures

        updated: list[OwnBlob] = []
        for own in sorted(survivors, key=lambda item: item.radius, reverse=True):
            current = own
            still_remaining: list[EnemyBlob] = []
            for enemy in remaining:
                if (
                    can_eat_player_blob(current.radius, enemy.radius)
                    and squared_distance(current.pos, enemy.pos) <= current.radius * current.radius
                ):
                    current = replace(current, radius=math.sqrt(current.mass + enemy.mass))
                    captured_enemy_ids.add(enemy.key)
                    score += 52.0 * enemy.mass + 40.0
                    captures += 1
                else:
                    still_remaining.append(enemy)
            remaining = still_remaining
            updated.append(current)
        return updated, tuple(remaining), score, captures

    def _risk_score(
        self,
        own_blobs: list[OwnBlob],
        enemies: tuple[EnemyBlob, ...],
        safety_weight: float,
    ) -> tuple[float, float, bool]:
        penalty = 0.0
        min_margin = math.inf
        endangered_blob_ids: set[int] = set()
        for own in own_blobs:
            for enemy in enemies:
                if not can_eat_player_blob(enemy.radius, own.radius):
                    continue
                distance = math.dist(own.pos, enemy.pos)
                normal_margin = distance - enemy.radius
                danger_radius = enemy.radius
                if _can_split_eat(enemy.radius, own.radius):
                    danger_radius = max(danger_radius, _split_attack_reach(enemy.radius))
                split_margin = distance - danger_radius
                margin = min(normal_margin, split_margin)
                min_margin = min(min_margin, margin)
                uncertainty = 1.0 + enemy.stale_rounds * 0.12
                if margin <= 0.0:
                    endangered_blob_ids.add(own.blob_id)
                    penalty += (440.0 + 75.0 * own.mass + min(180.0, -margin * 35.0)) * uncertainty
                elif margin < 9.0:
                    penalty += (75.0 / (margin + 0.25) + (9.0 - margin) * 2.2) * uncertainty
        unavoidable = bool(own_blobs) and len(endangered_blob_ids) == len(own_blobs)
        return penalty * safety_weight, min_margin, unavoidable

    def _position_value(
        self,
        own_blobs: list[OwnBlob],
        enemies: tuple[EnemyBlob, ...],
        foods: tuple[FoodModel, ...],
        eaten_food_ids: set[int],
        arena_size: float,
        aggression: float,
    ) -> float:
        value = 0.0
        primary = max(own_blobs, key=lambda blob: blob.radius)

        available = [food for food in foods if food.food_id not in eaten_food_ids]
        if available:
            distances = sorted(
                min(math.dist(blob.pos, food.pos) for blob in own_blobs)
                for food in available
            )
            value += sum(2.0 / (distance + 1.0) for distance in distances[:8])

        for enemy in enemies:
            if enemy.stale_rounds:
                continue
            distance = math.dist(primary.pos, enemy.pos)
            if can_eat_player_blob(primary.radius, enemy.radius):
                gap = max(0.0, distance - primary.radius)
                value += aggression * min(9.0, enemy.mass * 3.2 / (gap + 1.0))
            elif not can_eat_player_blob(enemy.radius, primary.radius) and distance < 8.0:
                value -= (8.0 - distance) * 0.3
        return value

    def _escape_vector(self, node: SearchNode) -> tuple[float, float]:
        x = 0.0
        y = 0.0
        for own in node.own_blobs:
            for enemy in node.enemies:
                if not can_eat_player_blob(enemy.radius, own.radius):
                    continue
                danger_radius = enemy.radius
                if _can_split_eat(enemy.radius, own.radius):
                    danger_radius = max(danger_radius, _split_attack_reach(enemy.radius))
                distance = math.dist(own.pos, enemy.pos)
                if distance > danger_radius + 8.0:
                    continue
                away = normalise((own.x - enemy.x, own.y - enemy.y))
                severity = max(0.2, danger_radius + 8.0 - distance) / max(distance, 0.25)
                weight = severity * own.mass * (1.0 + enemy.stale_rounds * 0.1)
                x += away[0] * weight
                y += away[1] * weight
        return normalise((x, y))

    def _wall_vector(self, blob: OwnBlob, arena_size: float) -> tuple[float, float]:
        margin = blob.radius + 4.0
        x = max(0.0, (margin - blob.x) / margin)
        x -= max(0.0, (blob.x - (arena_size - margin)) / margin)
        y = max(0.0, (margin - blob.y) / margin)
        y -= max(0.0, (blob.y - (arena_size - margin)) / margin)
        return normalise((x, y))

    def _food_targets(
        self,
        center: tuple[float, float],
        foods: list[FoodModel],
    ) -> list[tuple[float, float]]:
        if not foods:
            return []
        nearest = min(foods, key=lambda food: squared_distance(center, food.pos))
        scored: list[tuple[float, tuple[float, float]]] = []
        for food in foods:
            neighbours = [other for other in foods if squared_distance(food.pos, other.pos) <= 9.0]
            target = (
                sum(other.pos[0] for other in neighbours) / len(neighbours),
                sum(other.pos[1] for other in neighbours) / len(neighbours),
            )
            distance = math.dist(center, target)
            score = (len(neighbours) + 0.5) / (distance + 1.5)
            scored.append((score, target))
        scored.sort(reverse=True)
        targets: list[tuple[float, float]] = [nearest.pos]
        seen: set[tuple[int, int]] = {(round(nearest.pos[0] * 2), round(nearest.pos[1] * 2))}
        for _, target in scored:
            key = (round(target[0] * 2), round(target[1] * 2))
            if key in seen:
                continue
            seen.add(key)
            targets.append(target)
        return targets

    def _nearest_food_pairs(
        self,
        node: SearchNode,
        foods: list[FoodModel],
    ) -> list[tuple[OwnBlob, FoodModel]]:
        scored: list[tuple[float, float, int, OwnBlob, FoodModel]] = []
        for food in foods:
            origin = min(
                node.own_blobs,
                key=lambda blob: squared_distance(blob.pos, food.pos),
            )
            distance = math.dist(origin.pos, food.pos)
            effective_gap = max(0.0, distance - origin.radius)
            scored.append(
                (
                    effective_gap,
                    squared_distance(node.center, food.pos),
                    food.food_id,
                    origin,
                    food,
                )
            )
        scored.sort(key=lambda item: (item[0], item[1], item[2]))
        return [(origin, food) for _, _, _, origin, food in scored]

    def _edge_food_actions(
        self,
        *,
        node: SearchNode,
        foods: list[FoodModel],
        arena_size: float,
        limit: int,
    ) -> list[Action]:
        scored: list[tuple[float, int, Action]] = []
        for origin, food in self._nearest_food_pairs(node, foods):
            x, y = food.pos
            edge_distances = (
                (x, "left"),
                (arena_size - x, "right"),
                (y, "bottom"),
                (arena_size - y, "top"),
            )
            edge_distance, edge = min(edge_distances, key=lambda item: item[0])
            if edge_distance > max(1.25, FOOD_RADIUS * 5.0):
                continue

            if edge == "left":
                dock = (origin.radius, y)
                lane = (-0.30, _sign(y - origin.y))
            elif edge == "right":
                dock = (arena_size - origin.radius, y)
                lane = (0.30, _sign(y - origin.y))
            elif edge == "bottom":
                dock = (x, origin.radius)
                lane = (_sign(x - origin.x), -0.30)
            else:
                dock = (x, arena_size - origin.radius)
                lane = (_sign(x - origin.x), 0.30)

            distance = math.dist(origin.pos, food.pos)
            dock_direction = normalise((dock[0] - origin.x, dock[1] - origin.y))
            if dock_direction != (0.0, 0.0):
                scored.append((distance, food.food_id, Action(dock_direction, reason="wall_food_dock")))
            lane_direction = normalise(lane)
            if lane_direction != (0.0, 0.0):
                scored.append((distance + 0.05, food.food_id, Action(lane_direction, reason="wall_food_lane")))

        scored.sort(key=lambda item: (item[0], item[1]))
        actions: list[Action] = []
        seen: set[tuple[int, bool]] = set()
        for _, _, action in scored:
            direction = normalise(action.direction)
            angle_bin = int(round(math.atan2(direction[1], direction[0]) / TAU * 96)) % 96
            key = (angle_bin, action.split)
            if key in seen:
                continue
            seen.add(key)
            actions.append(action)
            if len(actions) >= limit:
                break
        return actions


    def _direct_virus_decision(
        self,
        *,
        own_blobs: tuple[OwnBlob, ...],
        enemies: tuple[EnemyBlob, ...],
        viruses: tuple[VirusModel, ...],
        arena_size: float,
        rank_position: int,
        progress: float,
    ) -> Action | None:
        if not viruses or not own_blobs:
            return None
        if progress >= 0.74 and rank_position <= 2:
            return None
        pseudo = SearchNode(
            own_blobs=own_blobs,
            enemies=enemies,
            score=0.0,
            first_direction=self.previous_direction,
            first_split=False,
            first_reason="direct_virus",
            last_direction=self.previous_direction,
        )
        scored: list[tuple[float, int, Action]] = []
        for virus in viruses:
            candidates = [blob for blob in own_blobs if _can_consume_virus(blob.radius, virus.radius)]
            if not candidates:
                continue
            origin = min(candidates, key=lambda blob: squared_distance(blob.pos, virus.pos))
            gap = max(0.0, math.dist(origin.pos, virus.pos) - origin.radius - virus.radius)
            if gap > 13.0:
                continue
            piece_count = _virus_piece_count(len(own_blobs))
            piece_mass = (origin.mass + virus.radius * virus.radius) / piece_count
            if len(own_blobs) <= 3:
                if piece_mass < 0.30:
                    continue
                if not self._virus_local_area_is_clear(pseudo, origin, virus) and piece_mass < 0.58:
                    continue
            elif piece_mass < 0.40 and len(own_blobs) < 12:
                continue
            if self._virus_pop_exposes_every_fragment(pseudo, origin, virus, math.sqrt(piece_mass), piece_count, arena_size):
                continue
            direction = normalise((virus.pos[0] - origin.x, virus.pos[1] - origin.y))
            if direction == (0.0, 0.0):
                continue
            # Prefer committed contact once in range; otherwise allow the beam
            # to handle ordinary food if the virus is still far away.
            urgency = 0.0
            if gap <= 3.2:
                urgency -= 12.0
            elif len(own_blobs) >= 12:
                urgency -= 5.0
            elif origin.mass >= 3.2:
                urgency -= 3.0
            score = gap + urgency - min(piece_mass, 1.2) * 1.5
            scored.append((score, virus.virus_id, Action(direction, reason="direct_virus")))
        if not scored:
            return None
        scored.sort(key=lambda item: (item[0], item[1]))
        # Only override the search when the contact is near or the player is
        # already split enough that virus is low-risk mass.
        best_score, _, action = scored[0]
        if best_score <= 5.2 or len(own_blobs) >= 12:
            return action
        return None

    def _virus_actions(
        self,
        *,
        node: SearchNode,
        viruses: tuple[VirusModel, ...],
        arena_size: float,
        limit: int,
    ) -> list[Action]:
        scored: list[tuple[float, int, Action]] = []
        for virus in viruses:
            if virus.virus_id in node.consumed_virus_ids:
                continue
            candidates = [
                blob
                for blob in node.own_blobs
                if _can_consume_virus(blob.radius, virus.radius)
            ]
            if not candidates:
                continue
            origin = min(candidates, key=lambda blob: squared_distance(blob.pos, virus.pos))
            if not self._virus_entry_is_worthwhile(node, origin, virus, arena_size):
                continue
            direction = normalise((virus.pos[0] - origin.x, virus.pos[1] - origin.y))
            if direction == (0.0, 0.0):
                continue
            gap = max(0.0, math.dist(origin.pos, virus.pos) - origin.radius - virus.radius)
            piece_count = _virus_piece_count(len(node.own_blobs))
            after_piece_mass = (origin.mass + virus.radius * virus.radius) / piece_count
            cap_bonus = 5.0 if len(node.own_blobs) >= MAX_BLOB_COUNT else 0.0
            score = gap - min(2.5, after_piece_mass) - cap_bonus
            scored.append((score, virus.virus_id, Action(direction, reason="virus_harvest")))

            # Approach a virus from the side opposite a predator so the virus can
            # remain a shield if the final contact becomes unsafe.
            shield = self._virus_shield_direction(node, origin, virus)
            if shield != (0.0, 0.0):
                scored.append((score + 0.35, virus.virus_id, Action(shield, reason="virus_shield")))

        scored.sort(key=lambda item: (item[0], item[1]))
        actions: list[Action] = []
        seen: set[tuple[int, bool]] = set()
        for _, _, action in scored:
            direction = normalise(action.direction)
            angle_bin = int(round(math.atan2(direction[1], direction[0]) / TAU * 96)) % 96
            key = (angle_bin, action.split)
            if key in seen:
                continue
            seen.add(key)
            actions.append(action)
            if len(actions) >= limit:
                break
        return actions

    def _virus_entry_is_worthwhile(
        self,
        node: SearchNode,
        origin: OwnBlob,
        virus: VirusModel,
        arena_size: float,
    ) -> bool:
        piece_count = _virus_piece_count(len(node.own_blobs))
        virus_mass = virus.radius * virus.radius
        piece_mass = (origin.mass + virus_mass) / piece_count
        piece_radius = math.sqrt(piece_mass)
        total_after = node.total_mass + virus_mass
        gap = max(0.0, math.dist(origin.pos, virus.pos) - origin.radius - virus.radius)

        # At the blob cap, virus contact is pure mass gain.  With many existing
        # fragments, the new split count is small enough to be acceptable if the
        # local predator check passes.
        if len(node.own_blobs) >= MAX_BLOB_COUNT:
            min_piece_mass = 0.0
        elif len(node.own_blobs) >= 12:
            min_piece_mass = 0.42
        elif len(node.own_blobs) >= 8:
            min_piece_mass = 0.55
        elif len(node.own_blobs) >= 4:
            min_piece_mass = 0.62
        else:
            min_piece_mass = 0.32 if self._virus_local_area_is_clear(node, origin, virus) else 0.86
        if piece_mass < min_piece_mass and not self._virus_pop_has_predator_trade(node, origin, virus):
            return False

        if gap > 16.0 and len(node.own_blobs) < 10:
            return False
        if gap > 11.0 and total_after < 4.8:
            return False

        # Avoid harvesting at an edge when the generated grid would be clamped
        # into a predator path; use wall food / center movement instead.
        if (
            virus.pos[0] < piece_radius * 2.2
            or virus.pos[0] > arena_size - piece_radius * 2.2
            or virus.pos[1] < piece_radius * 2.2
            or virus.pos[1] > arena_size - piece_radius * 2.2
        ) and len(node.own_blobs) <= 3 and piece_mass < 1.05:
            return False

        if self._virus_pop_exposes_every_fragment(node, origin, virus, piece_radius, piece_count, arena_size):
            return False
        return True


    def _virus_local_area_is_clear(self, node: SearchNode, origin: OwnBlob, virus: VirusModel) -> bool:
        for enemy in node.enemies:
            if enemy.stale_rounds > 5:
                continue
            distance_to_origin = math.dist(origin.pos, enemy.pos)
            distance_to_virus = math.dist(virus.pos, enemy.pos)
            probe_radius = max(0.58, origin.radius / 2.4)
            if can_eat_player_blob(enemy.radius, probe_radius) and min(distance_to_origin, distance_to_virus) < 15.0:
                return False
            if _can_split_eat(enemy.radius, probe_radius) and min(distance_to_origin, distance_to_virus) < 19.0:
                return False
        return True

    def _virus_pop_has_predator_trade(self, node: SearchNode, origin: OwnBlob, virus: VirusModel) -> bool:
        # If a predator is between us and the virus, popping can force it to
        # cross the virus.  This is a weak allowance and still goes through the
        # post-pop safety check.
        to_virus = normalise((virus.pos[0] - origin.x, virus.pos[1] - origin.y))
        if to_virus == (0.0, 0.0):
            return False
        for enemy in node.enemies:
            if enemy.stale_rounds:
                continue
            rel = (enemy.x - origin.x, enemy.y - origin.y)
            forward = rel[0] * to_virus[0] + rel[1] * to_virus[1]
            lateral = abs(rel[0] * to_virus[1] - rel[1] * to_virus[0])
            if 0.0 < forward < math.dist(origin.pos, virus.pos) + virus.radius and lateral < virus.radius + 0.8:
                return True
        return False

    def _virus_pop_exposes_every_fragment(
        self,
        node: SearchNode,
        origin: OwnBlob,
        virus: VirusModel,
        piece_radius: float,
        piece_count: int,
        arena_size: float,
    ) -> bool:
        fragments = self._virus_replacement_fragments(
            origin=origin,
            virus=virus,
            piece_radius=piece_radius,
            piece_count=piece_count,
            arena_size=arena_size,
        )
        other_blobs = [blob for blob in node.own_blobs if blob.blob_id != origin.blob_id]
        post_blobs = other_blobs + fragments
        if not post_blobs:
            return True
        endangered = 0
        for blob in post_blobs:
            if self._blob_under_predator_envelope(blob, node.enemies):
                endangered += 1
        return endangered == len(post_blobs)

    def _blob_under_predator_envelope(
        self,
        blob: OwnBlob,
        enemies: tuple[EnemyBlob, ...],
    ) -> bool:
        for enemy in enemies:
            if not can_eat_player_blob(enemy.radius, blob.radius):
                continue
            distance = math.dist(blob.pos, enemy.pos)
            danger_radius = enemy.radius
            if _can_split_eat(enemy.radius, blob.radius):
                danger_radius = max(danger_radius, _split_attack_reach(enemy.radius))
            # One extra own-speed allowance accounts for the move after popping.
            if distance <= danger_radius + _speed(blob.radius) + 0.6 + enemy.stale_rounds * 0.35:
                return True
        return False

    def _virus_shield_direction(
        self,
        node: SearchNode,
        origin: OwnBlob,
        virus: VirusModel,
    ) -> tuple[float, float]:
        predator = None
        best_distance = math.inf
        for enemy in node.enemies:
            if not can_eat_player_blob(enemy.radius, origin.radius) and not _can_split_eat(enemy.radius, origin.radius):
                continue
            distance = math.dist(origin.pos, enemy.pos)
            if distance < best_distance:
                best_distance = distance
                predator = enemy
        if predator is None or best_distance > 16.0:
            return (0.0, 0.0)
        desired = (
            virus.pos[0] - predator.x,
            virus.pos[1] - predator.y,
        )
        if desired == (0.0, 0.0):
            return (0.0, 0.0)
        # Move toward the far side of the virus, not directly into it.
        far_side = (
            virus.pos[0] + normalise(desired)[0] * (virus.radius + origin.radius * 0.7),
            virus.pos[1] + normalise(desired)[1] * (virus.radius + origin.radius * 0.7),
        )
        return normalise((far_side[0] - origin.x, far_side[1] - origin.y))

    def _resolve_own_viruses(
        self,
        *,
        own_blobs: list[OwnBlob],
        viruses: tuple[VirusModel, ...],
        consumed_virus_ids: set[int],
        arena_size: float,
    ) -> tuple[list[OwnBlob], float, float]:
        score = 0.0
        penalty = 0.0
        for virus in viruses:
            if virus.virus_id in consumed_virus_ids:
                continue
            candidates = [
                (index, blob)
                for index, blob in enumerate(own_blobs)
                if _can_consume_virus(blob.radius, virus.radius)
                and squared_distance(blob.pos, virus.pos) <= (blob.radius + virus.radius) ** 2
            ]
            if not candidates:
                for blob in own_blobs:
                    if not _can_consume_virus(blob.radius, virus.radius):
                        continue
                    clearance = math.dist(blob.pos, virus.pos) - blob.radius - virus.radius
                    if clearance < 3.2:
                        # Being near a consumable virus is useful when already
                        # split/capped, otherwise it is a controllability risk.
                        if len(own_blobs) >= 12:
                            score += (3.2 - clearance) * 0.9
                        else:
                            penalty += (3.2 - clearance) ** 2 * 1.35
                continue

            index, blob = min(candidates, key=lambda item: (-item[1].radius, item[0]))
            consumed_virus_ids.add(virus.virus_id)
            virus_mass = virus.radius * virus.radius
            piece_count = _virus_piece_count(len(own_blobs))
            total_mass = blob.mass + virus_mass
            piece_mass = total_mass / piece_count
            piece_radius = math.sqrt(piece_mass)
            fragments = self._virus_replacement_fragments(
                origin=blob,
                virus=virus,
                piece_radius=piece_radius,
                piece_count=piece_count,
                arena_size=arena_size,
            )
            own_blobs = own_blobs[:index] + fragments + own_blobs[index + 1 :]

            # Value virus mass as roughly food_count gained, but price the
            # controllability cost of many small fragments.
            score += 70.0 + virus_mass * 13.0
            if piece_count > 1:
                small_piece_penalty = max(0.0, 0.85 - piece_mass) * piece_count * 18.0
                score -= small_piece_penalty
                penalty += max(0, piece_count - 4) * 3.5
        return own_blobs, score, penalty

    def _virus_replacement_fragments(
        self,
        *,
        origin: OwnBlob,
        virus: VirusModel,
        piece_radius: float,
        piece_count: int,
        arena_size: float,
    ) -> list[OwnBlob]:
        if piece_count <= 1:
            return [replace(origin, radius=piece_radius, x=_clamp(origin.x, piece_radius, arena_size - piece_radius), y=_clamp(origin.y, piece_radius, arena_size - piece_radius))]
        cols = math.ceil(math.sqrt(piece_count))
        rows = math.ceil(piece_count / cols)
        spacing = piece_radius * 2.0 + SAME_PLAYER_OVERLAP_EPSILON
        x_offset = (cols - 1) * spacing / 2.0
        y_offset = (rows - 1) * spacing / 2.0
        fragments: list[OwnBlob] = []
        next_id = origin.blob_id
        for index in range(piece_count):
            row = index // cols
            col = index % cols
            x = origin.x + col * spacing - x_offset
            y = origin.y + row * spacing - y_offset
            fragments.append(
                OwnBlob(
                    blob_id=next_id if index == 0 else origin.blob_id + 1000 + index,
                    x=_clamp(x, piece_radius, arena_size - piece_radius),
                    y=_clamp(y, piece_radius, arena_size - piece_radius),
                    radius=piece_radius,
                    merge_cooldown=SPLIT_COOLDOWN_FRAMES,
                )
            )
        return fragments

    def _intercept_direction(self, own: OwnBlob, enemy: EnemyBlob) -> tuple[float, float]:
        distance = math.dist(own.pos, enemy.pos)
        lookahead = min(3.0, distance / max(_speed(own.radius), 0.1) * 0.3)
        target = (
            enemy.x + enemy.direction[0] * _speed(enemy.radius) * lookahead,
            enemy.y + enemy.direction[1] * _speed(enemy.radius) * lookahead,
        )
        return normalise((target[0] - own.x, target[1] - own.y))

    def _split_can_capture(
        self,
        node: SearchNode,
        enemy: EnemyBlob,
        direction: tuple[float, float],
    ) -> bool:
        if len(node.own_blobs) >= MAX_BLOB_COUNT:
            return False
        eligible = [blob for blob in node.own_blobs if blob.mass >= SPLIT_MIN_MASS]
        if not eligible:
            return False
        for blob in eligible:
            child_radius = blob.radius / SQRT2
            if not can_eat_player_blob(child_radius, enemy.radius):
                continue
            rel = (enemy.x - blob.x, enemy.y - blob.y)
            forward = rel[0] * direction[0] + rel[1] * direction[1]
            lateral = abs(rel[0] * direction[1] - rel[1] * direction[0])
            reach = 2.0 * child_radius + SPLIT_EJECT_SPEED + _speed(child_radius) + child_radius
            if -0.1 <= forward <= reach and lateral <= child_radius:
                return True
        return False

    def _safe_farm_split(
        self,
        node: SearchNode,
        foods: list[FoodModel],
        food_targets: tuple[tuple[float, float], ...],
    ) -> Action | None:
        if len(node.own_blobs) != 1 or node.primary.mass < 3.4 or len(foods) < 5:
            return None
        primary = node.primary
        if any(
            can_eat_player_blob(enemy.radius, primary.radius / SQRT2)
            and math.dist(primary.pos, enemy.pos) < 14.0
            for enemy in node.enemies
        ):
            return None
        if not food_targets:
            return None
        target = food_targets[0]
        direction = normalise((target[0] - primary.x, target[1] - primary.y))
        along = 0
        for food in foods:
            rel = (food.pos[0] - primary.x, food.pos[1] - primary.y)
            forward = rel[0] * direction[0] + rel[1] * direction[1]
            lateral = abs(rel[0] * direction[1] - rel[1] * direction[0])
            if 0.0 <= forward <= 9.0 and lateral <= primary.radius * 1.4:
                along += 1
        if along < 4:
            return None
        return Action(direction, split=True, reason="split_farm")

    def _prune(self, candidates: list[SearchNode]) -> list[SearchNode]:
        candidates.sort(key=self._terminal_score, reverse=True)
        kept: list[SearchNode] = []
        seen: set[tuple[int, bool, int, int, int]] = set()
        for node in candidates:
            center = node.center
            first_angle = int(round(math.atan2(node.first_direction[1], node.first_direction[0]) / TAU * 48)) % 48
            key = (
                first_angle,
                node.first_split,
                round(center[0] * 2),
                round(center[1] * 2),
                len(node.own_blobs),
            )
            if key in seen:
                continue
            seen.add(key)
            kept.append(node)
            if len(kept) >= max(1, self.width):
                break
        return kept

    def _terminal_score(self, node: SearchNode) -> float:
        if not node.own_blobs:
            return node.score
        # Mass is counted only at the frontier, avoiding a bias toward gains
        # that happen earlier merely because they are re-added every depth.
        return node.score + math.log1p(node.total_mass) * 5.0

    def _replace_node(
        self,
        *,
        node: SearchNode,
        own_blobs: tuple[OwnBlob, ...] | list[OwnBlob],
        enemies: tuple[EnemyBlob, ...],
        score: float,
        direction: tuple[float, float],
        action: Action,
        first_step: bool,
        eaten_food_ids: set[int],
        captured_enemy_ids: set[tuple[int, int]],
        consumed_virus_ids: set[int],
        projected_food: int,
        projected_captures: int,
        min_safety_margin: float,
    ) -> SearchNode:
        return SearchNode(
            own_blobs=tuple(own_blobs),
            enemies=enemies,
            score=score,
            first_direction=direction if first_step else node.first_direction,
            first_split=action.split if first_step else node.first_split,
            first_reason=action.reason if first_step else node.first_reason,
            last_direction=direction,
            eaten_food_ids=frozenset(eaten_food_ids),
            captured_enemy_ids=frozenset(captured_enemy_ids),
            consumed_virus_ids=frozenset(consumed_virus_ids),
            projected_food=projected_food,
            projected_captures=projected_captures,
            min_safety_margin=min_safety_margin,
        )

    def _dedupe_actions(self, actions: list[Action]) -> tuple[Action, ...]:
        result: list[Action] = []
        seen: set[tuple[int, bool]] = set()
        for action in actions:
            direction = normalise(action.direction)
            if direction == (0.0, 0.0):
                continue
            angle_bin = int(round(math.atan2(direction[1], direction[0]) / TAU * 96)) % 96
            key = (angle_bin, action.split)
            if key in seen:
                continue
            seen.add(key)
            result.append(Action(direction, action.split, action.reason))
        return tuple(result)

    def _mass_center(self, blobs: tuple[OwnBlob, ...]) -> tuple[float, float]:
        total = sum(blob.mass for blob in blobs)
        return (
            sum(blob.x * blob.mass for blob in blobs) / total,
            sum(blob.y * blob.mass for blob in blobs) / total,
        )

    def _rank_position(self, rankings: list[int], player_id: int) -> int:
        try:
            return list(rankings).index(player_id) + 1
        except ValueError:
            return 8

    def _safety_weight(self, rank_position: int, progress: float) -> float:
        if progress >= 0.72 and rank_position <= 2:
            return 1.8
        if progress >= 0.88:
            return 1.35
        return 1.0

    def _aggression(self, rank_position: int, progress: float) -> float:
        if progress >= 0.75 and rank_position >= 5:
            return 1.45
        if progress >= 0.72 and rank_position <= 2:
            return 0.72
        return 1.0

    def _turn_cost(
        self,
        previous: tuple[float, float],
        current: tuple[float, float],
    ) -> float:
        previous = normalise(previous)
        current = normalise(current)
        dot = _clamp(previous[0] * current[0] + previous[1] * current[1], -1.0, 1.0)
        return (1.0 - dot) * 0.35


def _speed(radius: float) -> float:
    return max(MIN_PLAYER_SPEED, BASE_PLAYER_SPEED / (1.0 + radius * PLAYER_SPEED_RADIUS_FACTOR))


def _decayed_radius(radius: float) -> float:
    mass = radius * radius
    minimum = STARTING_RADIUS * STARTING_RADIUS
    if mass <= minimum:
        return radius
    return math.sqrt(max(minimum, mass * (1.0 - MASS_DECAY_RATE)))


def _virus_piece_count(current_blob_count: int) -> int:
    return max(1, MAX_BLOB_COUNT - current_blob_count + 1)


def _can_consume_virus(blob_radius: float, virus_radius: float) -> bool:
    return blob_radius * blob_radius > virus_radius * virus_radius * EAT_SIZE_RATIO


def _can_split_eat(predator_radius: float, prey_radius: float) -> bool:
    return (
        predator_radius * predator_radius >= SPLIT_MIN_MASS
        and can_eat_player_blob(predator_radius / SQRT2, prey_radius)
    )


def _split_attack_reach(predator_radius: float) -> float:
    """One-round center-distance reach of a directly aimed split attack."""

    child_radius = predator_radius / SQRT2
    return 3.0 * child_radius + SPLIT_EJECT_SPEED + _speed(child_radius)


def _damped(value: float) -> float:
    value *= SPLIT_EJECT_DRAG
    return 0.0 if abs(value) < 1e-4 else value


def _rotate(direction: tuple[float, float], angle: float) -> tuple[float, float]:
    direction = normalise(direction)
    cosine = math.cos(angle)
    sine = math.sin(angle)
    return (
        direction[0] * cosine - direction[1] * sine,
        direction[0] * sine + direction[1] * cosine,
    )


def _sign(value: float) -> float:
    if value > 0.0:
        return 1.0
    if value < 0.0:
        return -1.0
    return 0.0


def _clamp(value: float, lower: float, upper: float) -> float:
    return min(max(value, lower), upper)


def main() -> None:
    game = Game()
    strategy = ChampionStrategy()

    while True:
        try:
            query = game.get_next_query()
        except EOFError:
            break

        match query:
            case QueryMovePlayer():
                decision = strategy.choose(StrategyContext(game=game, query=query))
                game.send_move(decision.to_move(game.state.me.player_id))
            case _:
                raise RuntimeError(f"Unsupported query type: {type(query)}")


if __name__ == "__main__":
    main()
